/* GENERATED by scripts/gen-blog-index.js. Do not edit by hand. */

import aurora from "./aurora";
import engine from "./engine";
import fargate from "./fargate";
import triage from "./triage";

export const posts = [fargate, engine, aurora, triage];
